---
- name: Load application bundle
  include_vars:
    file: "{{ APP_BUNDLE_FILE_PATH }}"
    name: app_bundle

- name: Update the application service directly using application name
  uri:
    url: "{{ control_plane_url }}/runtime/update"
    method: POST
    body_format: json
    body:
      version: "{{ app_bundle.application.version }}"
      applicationName: "{{ app_bundle.application.name }}"
      serviceName: "{{ app_bundle.service.name }}"
    status_code: 200
    headers:
      Content-Type: "application/json"
      Authorization: "{{ auth_token }}"
  register: update_response

- name: Display update results
  debug:
    msg: "update response: {{ update_response }}"